#:schema https://mise.en.dev/schema/mise.json

[tools]
# tools
task = "latest"
tmux = "latest"
neovim = "latest"
sops = "latest"
lsd = "latest"
gh = "latest"
lazygit = "latest"
k9s = "latest"
slsa-verifier = "latest"
cosign = "latest"

# dev
go = "latest"
rust = "latest"
python = "latest"
uv = "latest"
node = "latest"
bun = "latest"
biome = "latest"

# search
fd = "latest"
fzf = "latest"
rg = "latest"
yq = "latest"

[settings]
disable_backends = ["asdf", "pipx"]
pipx.uvx = true
npm.package_manager = "bun"
experimental = true
