#:schema https://mise.en.dev/schema/mise.json

[tools]
# helpers
task = "latest"
tmux = "latest"
neovim = "latest"
sops = "latest"
lsd = "latest"
lazygit = "latest"
slsa-verifier = "latest"
cosign = "latest"

# search
fd = "latest"
fzf = "latest"
rg = "latest"
yq = "latest"
