---
# https://github.com/anishathalye/dotbot/tree/master#directives

- defaults:
    link:
      create: true
      relink: true

- clean:
    - "~"
    - "~/.config"
    - "~/.functions"
    - "~/.bin"

- link:
    ~/.bash_profile:
      path: base/.bash_profile
      force: true
    ~/.bashrc:
      path: base/.bashrc
      force: true
    ~/.dircolors:
      path: base/.dircolors
      if: "[ whence dircolors >/dev/null ]"
    ~/.zshrc:
      path: base/.zshrc
      if: '[ -x "$(command -v zsh)" ]'
    ~/.editorconfig:
      path: base/.editorconfig
    ~/.profile:
      path: base/.profile
    ~/.vimrc:
      path: base/.vimrc
      force: true
    ~/.vimrc.bundles:
      path: base/.vimrc.bundles
    ~/.tmux.conf:
      path: base/.tmux.conf
    ~/.config/nvim/lua/user/init.lua:
      path: base/.config/nvim/lua/user/init.lua
    ~/.bin/:
      glob: true
      path: base/.bin/*
    ~/.functions/:
      glob: true
      path: base/.functions/*

- shell:
    # Allow direnv access to ~/.envrc
    - ['[ -f "$HOME/.zinit/plugins/direnv---direnv/direnv" ] && direnv allow $HOME || true']
    - ['[ -f /bin/zsh ] && /bin/zsh -c "source ~/.zshrc; zinit self-update"']
    # Issue: https://github.com/wbthomason/packer.nvim/issues/751
    # -
    #   - >-
    #     [ -d "$HOME/.zinit/plugins/astronvim---astronvim" ] &&
    #     nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
    - ['doom upgrade']
    -
      # https://github.com/tmux-plugins/tpm/blob/master/docs/managing_plugins_via_cmd_line.md
      - >-
        tmux start\;
        new -d\;
        run "~/.tmux/plugins/tpm/bin/install_plugins"\;
        run "~/.tmux/plugins/tpm/bin/update_plugins all"\;
        kill-session
