---
- defaults:
    link:
      create: true
      relink: true

- create:
    - ~/dev
    - ~/dev/me
    - ~/dev/sandbox
    - ~/dev/work

- link:
    ~/.config/k9s/config.yaml:
      path: dev/.config/k9s/config.yaml
      if: '[[ "$OSTYPE" == "linux-gnu"* ]]'
    ~/.config/k9s/skins/skin.yaml:
      path: dev/.config/k9s/skin.yaml
      if: '[[ "$OSTYPE" == "linux-gnu"* ]]'
    ~/Library/Application Support/k9s/config.yaml:
      path: dev/.config/k9s/config.yaml
      if: '[[ "$OSTYPE" == "darwin"* ]]'
    ~/Library/Application Support/k9s/skins/skin.yaml:
      path: dev/.config/k9s/skin.yaml
      if: '[[ "$OSTYPE" == "darwin"* ]]'
    ~/.tool-versions:
      path: dev/.tool-versions
    ~/.iex.exs:
      path: dev/.iex.exs
    ~/.zshrc.dev:
      path: dev/.zshrc.dev
    ~/.config/nvim:
      path: dev/.config/nvim
    ~/.functions/:
      glob: true
      path: base/.functions/*

- shell:
    - ['nvim --headless "+Lazy! sync" -c "quitall"']
