#!/usr/bin/env bash

set -e

CONFIG="install.conf.yml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"

(cd "${DOTBOT_DIR}" && git submodule update --init --recursive)
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

# Local only dotfiles are deploy to `/local` from Ansible
SECONDARYDIR="${BASEDIR}/local"
if [[ -f "${SECONDARYDIR}/${CONFIG}" ]]; then
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${SECONDARYDIR}" -c "${SECONDARYDIR}/${CONFIG}" "${@}"
fi
