[tools]
prettier = "latest"
direnv = "latest"
gitleaks = "latest"
lefthook = "latest"
shellcheck = "latest"
task = "latest"
yamllint = "latest"

[settings]
disable_backends = ["asdf"]

[hooks]
enter = "mise i -q"
