watch = true
menu_bar = false
animations = false
agent_notes = true
prompt_save_view_preferences = false
transparent_background = true
theme = "github-dark-high-contrast"
mode = "auto"
line_numbers = true
wrap_lines = false
hunk_headers = true
copy_decorations = false
cursor_line = "row"
