[tools]

# tools
task = "latest"
sops = "latest"
lsd = "latest"
gh = "latest"
k9s = "latest"
slsa-verifier = "latest"
cosign = "latest"
claude = "latest"
opencode = "latest"

# dev
go = "latest"
rust = "latest"
python = "latest"
uv = "latest"
node = "latest"
bun = "latest"
biome = "latest"

# search
fd = "latest"
fzf = "latest"
"npm:@tobilu/qmd" = "latest"
rg = "latest"
ast-grep = "latest"
yq = "latest"

# containers
lima = "latest"
colima = "latest"
docker-cli = "latest"
[tools.docker-compose]
version = "latest"
postinstall = '''
mkdir -p ~/.docker/cli-plugins ~/.local/bin
compose_plugin="$(which docker-cli-plugin-docker-compose)"
ln -sf "$compose_plugin" ~/.docker/cli-plugins/docker-compose
ln -sf "$compose_plugin" ~/.local/bin/docker-compose
'''

[settings]
disable_backends = ["asdf", "pipx"]
pipx.uvx = true
npm.bun = true
experimental = true
