[tools]
biome = "latest"
bun = "latest"
cosign = "latest"
claude = "latest"
colima = "latest"
docker-cli = "latest"
docker-compose = "latest"
fd = "latest"
gh = "latest"
go = "latest"
k9s = "latest"
lima = "latest"
lsd = "latest"
node = "latest"
python = "latest"
rust = "latest"
slsa-verifier = "latest"
sops = "latest"
task = "latest"
uv = "latest"

[settings]
disable_backends = ["asdf", "pipx"]
pipx.uvx = true
npm.bun = true
experimental = true
