#!/usr/bin/env python3
"""Materialize an OpenCode profile from a common base plus an overlay."""
from __future__ import annotations

import json
import sys
from collections.abc import Mapping
from pathlib import Path
from typing import Any


def strip_jsonc_comments(text: str) -> str:
    output: list[str] = []
    index = 0
    in_string = False
    escaped = False
    while index < len(text):
        char = text[index]
        next_char = text[index + 1] if index + 1 < len(text) else ""
        if in_string:
            output.append(char)
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
            index += 1
        elif char == '"':
            in_string = True
            output.append(char)
            index += 1
        elif char == "/" and next_char == "/":
            index = text.find("\n", index)
            if index == -1:
                break
        elif char == "/" and next_char == "*":
            end = text.find("*/", index + 2)
            if end == -1:
                raise SystemExit("merge-profile: unterminated block comment")
            index = end + 2
        else:
            output.append(char)
            index += 1
    return "".join(output)


def strip_trailing_commas(text: str) -> str:
    output: list[str] = []
    index = 0
    in_string = False
    escaped = False
    while index < len(text):
        char = text[index]
        if in_string:
            output.append(char)
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
            index += 1
            continue
        if char == '"':
            in_string = True
        if char == ",":
            next_index = index + 1
            while next_index < len(text) and text[next_index].isspace():
                next_index += 1
            if next_index < len(text) and text[next_index] in "}]":
                index += 1
                continue
        output.append(char)
        index += 1
    return "".join(output)


def load_jsonc(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    data = json.loads(strip_trailing_commas(strip_jsonc_comments(text)))
    if not isinstance(data, dict):
        raise SystemExit(f"merge-profile: {path} must contain a JSON object")
    return data


def deep_merge(base: Mapping[str, Any], overlay: Mapping[str, Any]) -> dict[str, Any]:
    merged = dict(base)
    for key, value in overlay.items():
        base_value = merged.get(key)
        if isinstance(base_value, Mapping) and isinstance(value, Mapping):
            merged[key] = deep_merge(base_value, value)
        else:
            merged[key] = value
    return merged


def main(argv: list[str]) -> int:
    if len(argv) != 4:
        print("usage: merge-profile.py <common.jsonc> <profile.jsonc> <output.jsonc>", file=sys.stderr)
        return 2

    common_path = Path(argv[1])
    profile_path = Path(argv[2])
    output_path = Path(argv[3])
    merged = deep_merge(load_jsonc(common_path), load_jsonc(profile_path))
    header = (
        "// Generated by opencode-profile from ai/opencode/profiles/common.jsonc "
        f"+ ai/opencode/profiles/{profile_path.name}.\n"
        "// Edit those source files, not this generated config.\n"
    )
    output_path.write_text(header + json.dumps(merged, indent=2) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
