# CLI
brew "bat"
brew "btop"
brew "coreutils"
brew "fd"
brew "git"
brew "k9s"
brew "lsd"
brew "mas"
brew "neovim"
brew "qrencode"
brew "sops"
brew "terminal-notifier"
brew "tmux"
brew "trash-cli"
brew "wget"

# CLI + GUI
brew "wireguard-tools"

# Custom taps
cask "finestructure/hummingbird/hummingbird"

tap "deskflow/homebrew-tap"
cask "deskflow"

# GUI
cask "balenaetcher"
cask "bambu-studio"
cask "db-browser-for-sqlite"
cask "discord"
cask "docker"
cask "elgato-control-center"
cask "elgato-stream-deck"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "github"
cask "google-chrome"
cask "ungoogled-chromium"
cask "gpg-suite"
cask "hammerspoon"
cask "home-assistant"
cask "iterm2"
cask "karabiner-elements"
cask "kopiaui"
cask "maccy"
cask "plex"
cask "postico"
cask "raspberry-pi-imager"
cask "slack"
cask "stats"
cask "spotify"
cask "telegram"
cask "unnaturalscrollwheels"
cask "vnc-viewer"
cask "visual-studio-code"
cask "vlc"
cask "zoom"

# AppStore
mas "Bitwarden", id: 1352778147 # Safari support
mas "Home Assistant", id: 1099568401
mas "uBlock Origin Lite", id: 6745342698
mas "Windows App", id: 1295203466 # Microsoft Remote Desktop
mas "Xcode", id: 497799835
