# CLI
brew "btop"
brew "coreutils"
brew "flock"
brew "git"
brew "mas"
brew "wget"

# GUI
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "ungoogled-chromium"
cask "ghostty"
cask "gpg-suite"
cask "hammerspoon"
cask "maccy"

# AppStore
mas "Xcode", id: 497799835
