#!/usr/bin/env python3
"""Materialize a pi profile from a common base plus an overlay."""
from __future__ import annotations

import sys
from collections.abc import Mapping
from pathlib import Path
from typing import Any


def load_yaml(path: Path) -> dict[str, Any]:
    try:
        import yaml
    except ModuleNotFoundError as exc:
        raise SystemExit(f"merge-profile: PyYAML not available: {exc}") from exc

    with path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle) or {}
    if not isinstance(data, dict):
        raise SystemExit(f"merge-profile: {path} must contain a YAML mapping")
    return data


def deep_merge(base: Mapping[str, Any], overlay: Mapping[str, Any]) -> dict[str, Any]:
    merged = dict(base)
    for key, value in overlay.items():
        base_value = merged.get(key)
        if isinstance(base_value, Mapping) and isinstance(value, Mapping):
            merged[key] = deep_merge(base_value, value)
        else:
            merged[key] = value
    return merged


def main(argv: list[str]) -> int:
    if len(argv) != 4:
        print("usage: merge-profile.py <common.yml> <profile.yml> <output.yml>", file=sys.stderr)
        return 2

    common_path = Path(argv[1])
    profile_path = Path(argv[2])
    output_path = Path(argv[3])

    # Import the vendored PyYAML bundled with dotbot before falling back to site packages.
    dotfiles = Path(__file__).resolve().parents[2]
    sys.path.insert(0, str(dotfiles / "dotbot" / "lib" / "pyyaml" / "lib"))

    merged = deep_merge(load_yaml(common_path), load_yaml(profile_path))

    import yaml

    rendered = yaml.safe_dump(
        merged,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
    )
    header = (
        "# Generated by pi-profile from ai/pi/profiles/common.yml "
        f"+ ai/pi/profiles/{profile_path.name}.\n"
        "# Edit those source files, not this generated config.\n"
    )
    output_path.write_text(header + rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
