#!/bin/bash

NAME=$(basename "$0")

_usage() {
  cat <<- EOF
Usage:  $NAME [options]
        Mute the default PulseAudio source or otherwise every source

Options:
  -h      Display this message
  -d      Apply to default source only
  -y      Mute
  -n      Unmute
          Mute is toggled when -y or -n are not specified

EOF
}

ACTION="toggle"
DEFAULT_ONLY="false"

while getopts ":hdyn" OPT; do
  case $OPT in
    h)
      _usage
      exit 0
      ;;
    y)
      ACTION="1"
      ;;
    d)
      DEFAULT_ONLY="true"
      ;;
    n)
      ACTION="0"
      ;;
    *)
      echo -e "Option does not exist: -$OPTARG"
      _usage
      exit 1
      ;;
  esac
done
shift $((OPTIND - 1))

if [ $DEFAULT_ONLY = "true" ]; then
  pactl set-source-mute @DEFAULT_SOURCE@ "$ACTION"
else
  # Source: https://askubuntu.com/a/1152002/664421
  pacmd list-sources | \
    grep -oP 'index: \d+' | \
    awk '{ print $2 }' | \
    xargs -I{} pactl set-source-mute {} "$ACTION"
fi
