#!/usr/bin/env python3

import argparse
import json
import plistlib
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PALETTE_PATH = Path(__file__).with_suffix(".json")


def load_palette() -> dict:
    return json.loads(PALETTE_PATH.read_text())


def ghostty_theme(palette: dict) -> bytes:
    semantic = palette["semantic"]
    ansi = palette["ansi"]
    lines = [
        "# Generated by themes/kaile.py from themes/kaile.json.",
        f"background = {semantic['background']}",
        f"foreground = {semantic['foreground']}",
        f"cursor-color = {semantic['accent']}",
        f"cursor-text = {semantic['textOnAccent']}",
        f"selection-background = {semantic['surfaceSelection']}",
        f"selection-foreground = {semantic['textActive']}",
        "",
    ]
    lines.extend(f"palette = {index}={ansi[str(index)]}" for index in range(16))
    return ("\n".join(lines) + "\n").encode()


def iterm_color(value: str) -> dict:
    red, green, blue = (int(value[index : index + 2], 16) / 255 for index in (1, 3, 5))
    return {
        "Alpha Component": 1.0,
        "Blue Component": blue,
        "Color Space": "sRGB",
        "Green Component": green,
        "Red Component": red,
    }


def iterm_theme(palette: dict) -> bytes:
    semantic = palette["semantic"]
    ansi = palette["ansi"]
    colors = {f"Ansi {index} Color": iterm_color(ansi[str(index)]) for index in range(16)}
    colors.update(
        {
            "Background Color": iterm_color(semantic["background"]),
            "Bold Color": iterm_color(semantic["textActive"]),
            "Cursor Color": iterm_color(semantic["accent"]),
            "Cursor Guide Color": iterm_color(semantic["surfaceBorder"]),
            "Cursor Text Color": iterm_color(semantic["textOnAccent"]),
            "Foreground Color": iterm_color(semantic["foreground"]),
            "Selected Text Color": iterm_color(semantic["textActive"]),
            "Selection Color": iterm_color(semantic["surfaceSelection"]),
        }
    )
    return plistlib.dumps(colors, fmt=plistlib.FMT_XML, sort_keys=False)


def nvim_palette(palette: dict) -> bytes:
    s = palette["semantic"]
    a = palette["ansi"]
    text = f'''-- Generated by themes/kaile.py from themes/kaile.json.
local c = {{
  none = "NONE",
  syntax = {{}},
  ui = {{}},
  term = {{}},
  icon = {{}},
}}

--------------------------------
--- Syntax
--------------------------------
c.syntax.red = "{s['red']}"
c.syntax.orange = "{s['magenta']}"
c.syntax.yellow = "{s['yellow']}"
c.syntax.green = "{s['green']}"
c.syntax.cyan = "{s['cyan']}"
c.syntax.blue = "{s['blue']}"
c.syntax.purple = "{s['magenta']}"
c.syntax.text = "{s['foreground']}"
c.syntax.comment = "{s['textMuted']}"
c.syntax.mute = "{s['textMuted']}"

--------------------------------
--- UI
--------------------------------
c.ui.red = c.syntax.red
c.ui.orange = c.syntax.orange
c.ui.yellow = c.syntax.yellow
c.ui.green = c.syntax.green
c.ui.cyan = c.syntax.cyan
c.ui.blue = c.syntax.blue
c.ui.purple = c.syntax.purple

c.ui.accent = c.ui.green

c.ui.tabline = "{s['surfaceActive']}"
c.ui.winbar = "{s['foreground']}"
c.ui.tool = "{s['surfaceRaised']}"
c.ui.base = "{s['background']}"
c.ui.inactive_base = "{s['surfaceRaised']}"
c.ui.statusline = "{s['surfaceActive']}"
c.ui.split = "{s['surfaceBorder']}"
c.ui.float = "{s['surfaceRaised']}"
c.ui.title = c.ui.accent
c.ui.border = c.ui.blue
c.ui.current_line = "{s['surfaceActive']}"
c.ui.scrollbar = c.ui.accent
c.ui.selection = "{s['surfaceSelection']}"
c.ui.menu_selection = c.ui.selection
c.ui.highlight = "{s['surfaceHighlight']}"
c.ui.none_text = "{s['surfaceBorder']}"
c.ui.text = "{s['foreground']}"
c.ui.text_active = "{s['textActive']}"
c.ui.text_inactive = "{s['textMuted']}"
c.ui.text_match = c.ui.accent

c.ui.prompt = "{s['surfaceActive']}"

--------------------------------
--- Terminal
--------------------------------
c.term.black = "{a['0']}"
c.term.bright_black = "{a['8']}"
c.term.red = "{a['1']}"
c.term.bright_red = "{a['9']}"
c.term.green = "{a['2']}"
c.term.bright_green = "{a['10']}"
c.term.yellow = "{a['3']}"
c.term.bright_yellow = "{a['11']}"
c.term.blue = "{a['4']}"
c.term.bright_blue = "{a['12']}"
c.term.purple = "{a['5']}"
c.term.bright_purple = "{a['13']}"
c.term.cyan = "{a['6']}"
c.term.bright_cyan = "{a['14']}"
c.term.white = "{a['7']}"
c.term.bright_white = "{a['15']}"
c.term.background = c.ui.base
c.term.foreground = c.ui.text

--------------------------------
--- Icons
--------------------------------
c.icon.c = c.ui.blue
c.icon.css = c.ui.blue
c.icon.deb = c.ui.purple
c.icon.docker = c.ui.cyan
c.icon.html = c.ui.red
c.icon.jpeg = c.ui.purple
c.icon.jpg = c.ui.purple
c.icon.js = c.ui.yellow
c.icon.jsx = c.ui.cyan
c.icon.kt = c.ui.purple
c.icon.lock = c.ui.yellow
c.icon.lua = c.ui.blue
c.icon.mp3 = c.ui.purple
c.icon.mp4 = c.ui.purple
c.icon.out = c.ui.text
c.icon.png = c.ui.purple
c.icon.py = c.ui.yellow
c.icon.rb = c.ui.red
c.icon.robots = c.ui.text
c.icon.rpm = c.ui.red
c.icon.rs = c.ui.orange
c.icon.toml = c.ui.green
c.icon.ts = c.ui.blue
c.icon.ttf = c.ui.text
c.icon.vue = c.ui.green
c.icon.woff = c.ui.text
c.icon.woff2 = c.ui.text
c.icon.zip = c.ui.yellow

return c
'''
    return text.encode()


def outputs(palette: dict) -> dict[Path, bytes]:
    return {
        ROOT / "darwin/.config/ghostty/themes/kaile": ghostty_theme(palette),
        ROOT / "darwin/iterm2-themes/kaile.itermcolors": iterm_theme(palette),
        ROOT / "base/.config/nvim/lua/astrotheme/palettes/kaile.lua": nvim_palette(palette),
    }


def luminance(value: str) -> float:
    channels = [int(value[index : index + 2], 16) / 255 for index in (1, 3, 5)]
    linear = [channel / 12.92 if channel <= 0.04045 else ((channel + 0.055) / 1.055) ** 2.4 for channel in channels]
    return 0.2126 * linear[0] + 0.7152 * linear[1] + 0.0722 * linear[2]


def contrast(foreground: str, background: str) -> float:
    lighter, darker = sorted((luminance(foreground), luminance(background)), reverse=True)
    return (lighter + 0.05) / (darker + 0.05)


def resolve(palette: dict, reference: str) -> str:
    section, key = reference.split(".", 1)
    return palette[section][key]


def validate_contrast(palette: dict) -> list[str]:
    errors = []
    for pair in palette["contrastPairs"]:
        foreground = resolve(palette, pair["foreground"])
        background = resolve(palette, pair["background"])
        ratio = contrast(foreground, background)
        if ratio < pair["minimum"]:
            errors.append(
                f"{pair['name']}: {ratio:.2f}:1 is below {pair['minimum']:.2f}:1 "
                f"({foreground} on {background})"
            )
    return errors


def validate_manual_consumers(palette: dict) -> list[str]:
    errors = []
    semantic = palette["semantic"]
    allowed = {value.lower() for value in semantic.values()} | {
        value.lower() for value in palette["ansi"].values()
    }

    vscode_path = ROOT / "darwin/vscode/extensions/kaile-theme/themes/kaile-color-theme.json"
    for value in set(re.findall(r"#[0-9a-fA-F]{6,8}", vscode_path.read_text())):
        if value[:7].lower() not in allowed:
            errors.append(f"{vscode_path.relative_to(ROOT)} uses unknown color {value}")

    herdr_path = ROOT / "ai/herdr/config.toml"
    herdr = tomllib.loads(herdr_path.read_text())["theme"]["custom"]
    expected = {
        "active_row_bg": semantic["surfaceActive"],
        "selection_bg": semantic["surfaceSelection"],
        "surface0": semantic["surfaceRaised"],
        "surface1": semantic["surfaceActive"],
        "surface_dim": semantic["textOnBlue"],
    }
    if herdr != expected:
        errors.append(f"{herdr_path.relative_to(ROOT)} does not match semantic Kaile roles")
    return errors


def write_outputs(palette: dict) -> None:
    for path, content in outputs(palette).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
        print(f"wrote {path.relative_to(ROOT)}")


def check_outputs(palette: dict) -> int:
    errors = validate_contrast(palette) + validate_manual_consumers(palette)
    for path, expected in outputs(palette).items():
        if not path.exists() or path.read_bytes() != expected:
            errors.append(f"{path.relative_to(ROOT)} is not generated from themes/kaile.json")
    if errors:
        print("Kaile palette check failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1
    print("Kaile palette: generated files and semantic contrast pairs are valid")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate and validate the Kaile color palette")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="regenerate consumer theme files")
    mode.add_argument("--check", action="store_true", help="verify generated files and contrast")
    args = parser.parse_args()
    palette = load_palette()
    if args.write:
        write_outputs(palette)
        return 0
    return check_outputs(palette)


if __name__ == "__main__":
    raise SystemExit(main())
