"""Backlog source interfaces and adapters."""

from .base import (
    BacklogError,
    BacklogSource,
    DuplicateTaskIdError,
    MalformedBacklogError,
    MissingDependencyError,
    ReadOnlySourceError,
    SourceFingerprintMismatchError,
    Task,
    TaskState,
    TaskNotFoundError,
    WritebackError,
    WritebackStateError,
)
from .markdown import fingerprint_section, slugify_title
from .markdown import MarkdownBacklog, normalize_section_body, parse_markdown
from .beads import (
    AmbiguousExternalRefError,
    BeadNotFoundError,
    BeadStateError,
    BeadsClient,
    BeadsCommandError,
    BeadsError,
    DependencyResult,
    MaterializationResult,
    WritebackResult,
    import_task,
    source_metadata,
    writeback_task,
)


__all__ = [
    "BacklogError",
    "BacklogSource",
    "DuplicateTaskIdError",
    "MalformedBacklogError",
    "MissingDependencyError",
    "ReadOnlySourceError",
    "SourceFingerprintMismatchError",
    "Task",
    "TaskNotFoundError",
    "TaskState",
    "WritebackError",
    "WritebackStateError",
    "MarkdownBacklog",
    "normalize_section_body",
    "parse_markdown",
    "fingerprint_section",
    "slugify_title",
    "AmbiguousExternalRefError",
    "BeadNotFoundError",
    "BeadStateError",
    "BeadsClient",
    "BeadsCommandError",
    "BeadsError",
    "DependencyResult",
    "MaterializationResult",
    "WritebackResult",
    "import_task",
    "source_metadata",
    "writeback_task",
]
