from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


class AiInstallTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.home = Path(self.temporary.name)
        self.environment = {
            **os.environ,
            "DOTFILES": str(ROOT),
            "DOTFILES_AI_TOOLS": "all",
            "HOME": str(self.home),
        }

    def run_command(
        self, *arguments: str, expected_code: int = 0
    ) -> subprocess.CompletedProcess[str]:
        completed = subprocess.run(
            arguments,
            text=True,
            capture_output=True,
            cwd=ROOT,
            env=self.environment,
            check=False,
        )
        self.assertEqual(
            expected_code, completed.returncode, completed.stdout + completed.stderr
        )
        return completed

    def repository_status(self) -> str:
        completed = subprocess.run(
            ["git", "status", "--porcelain"],
            text=True,
            capture_output=True,
            cwd=ROOT,
            check=False,
        )
        self.assertEqual(0, completed.returncode, completed.stderr)
        return completed.stdout

    def load_yaml(self, text: str) -> object:
        yaml_path = str(ROOT / "dotbot/lib/pyyaml/lib")
        sys.path.insert(0, yaml_path)
        try:
            import yaml

            return yaml.safe_load(text)
        finally:
            sys.path.remove(yaml_path)

    def install_fake_mise(self) -> Path:
        fake_bin = self.home / "fake-bin"
        fake_bin.mkdir(exist_ok=True)
        log = self.home / "mise.log"
        mise = fake_bin / "mise"
        mise.write_text('#!/bin/sh\nprintf \'%s\\n\' "$*" >> "$HOME/mise.log"\n')
        mise.chmod(0o755)
        self.environment["MISE_BIN"] = str(mise)
        return log

    def install_fake_dcg(self) -> Path:
        dcg = self.home / "bin/dcg"
        dcg.parent.mkdir(exist_ok=True)
        dcg.write_text(
            """#!/usr/bin/env python3
import os
import sys
from pathlib import Path

target = sys.argv[2]
if target == "--opencode":
    path = Path(os.environ["HOME"]) / ".config/opencode/plugins/dcg-guard.js"
elif target == "--omp":
    path = Path(os.environ["HOME"]) / ".omp/agent/extensions/dcg-guard.ts"
else:
    raise SystemExit(f"unexpected arguments: {sys.argv[1:]}")
path.parent.mkdir(parents=True, exist_ok=True)
path.write_text("// generated guard for test\\n")
"""
        )
        dcg.chmod(0o755)
        self.environment["DCG_BIN"] = str(dcg)
        return dcg

    @staticmethod
    def agent_body(path: Path) -> str:
        _, _, remainder = path.read_text().partition("---\n")
        _, _, body = remainder.partition("\n---\n")
        return body.lstrip("\n")

    def test_command_adapters_are_generated_without_touching_unmanaged_files(
        self,
    ) -> None:
        before = self.repository_status()
        legacy = self.home / ".claude/commands/pr-review-draft.md"
        unmanaged = self.home / ".claude/commands/manual.md"
        legacy.parent.mkdir(parents=True)
        legacy.write_text(
            "---\ndescription: legacy\n---\n\n"
            "<!-- Generated by install-agent-commands. -->\n"
        )
        unmanaged.write_text("Unmanaged command\n")

        self.run_command("ai/.bin/install-agent-commands")

        generated = self.home / ".agents/skills/pr-review-draft/SKILL.md"
        self.assertIn("Generated by install-agent-commands.", generated.read_text())
        self.assertEqual(
            generated.read_text(),
            (self.home / ".claude/skills/pr-review-draft/SKILL.md").read_text(),
        )
        self.assertTrue(
            (self.home / ".config/opencode/commands/pr-review-draft.md").is_file()
        )
        self.assertFalse(legacy.exists())
        self.assertEqual("Unmanaged command\n", unmanaged.read_text())
        self.assertEqual(before, self.repository_status())

    def test_generated_skill_frontmatter_is_valid(self) -> None:
        self.run_command("ai/.bin/install-agent-commands")

        skills = list((self.home / ".agents/skills").glob("*/SKILL.md"))
        self.assertTrue(skills)
        for skill in skills:
            with self.subTest(skill=skill):
                text = skill.read_text()
                self.assertTrue(text.startswith("---\n"))
                metadata = self.load_yaml(text.split("---\n", 2)[1])
                self.assertIsInstance(metadata, dict)
                self.assertEqual(skill.parent.name, metadata["name"])

    def test_command_adapters_refuse_unmanaged_targets(self) -> None:
        skill_dir = self.home / ".agents/skills/pr-review-draft"
        skill_dir.mkdir(parents=True)
        skill = skill_dir / "SKILL.md"
        skill.write_text("Unmanaged skill\n")

        completed = self.run_command("ai/.bin/install-agent-commands", expected_code=1)

        self.assertIn("Refusing to overwrite unmanaged skill", completed.stderr)
        self.assertEqual("Unmanaged skill\n", skill.read_text())

    def test_agent_definitions_are_generated_from_one_shared_body(self) -> None:
        before = self.repository_status()
        self.run_command("ai/.bin/install-agents")

        shared_harnesses = (
            ".claude/agents",
            ".omp/agent/agents",
            ".pi/agent/agents",
            ".config/opencode/agents",
        )
        for role in ("executor", "oracle", "reviewer", "verifier", "writer"):
            generated = [self.home / directory / f"{role}.md" for directory in shared_harnesses]
            self.assertTrue(all(path.is_file() for path in generated), role)
            bodies = [self.agent_body(path) for path in generated]
            self.assertTrue(all(body == bodies[0] for body in bodies[1:]), role)

        self.assertTrue((self.home / ".codex/agents/executor.toml").is_file())
        self.assertTrue((self.home / ".omp/agent/agents/explore.md").is_file())
        self.assertFalse((self.home / ".claude/agents/explore.md").exists())
        self.assertEqual(before, self.repository_status())

    def test_agent_definitions_preserve_unmanaged_output_paths(self) -> None:
        agents = self.home / ".claude/agents"
        agents.mkdir(parents=True)
        unmanaged = agents / "oracle.md"
        unmanaged.write_text("Unmanaged agent\n")

        completed = self.run_command("ai/.bin/install-agents", expected_code=1)

        self.assertIn("Refusing to overwrite unmanaged agent", completed.stderr)
        self.assertEqual("Unmanaged agent\n", unmanaged.read_text())

        unmanaged.unlink()
        external = self.home / "external-agent.md"
        external.write_text("Linked agent\n")
        unmanaged.symlink_to(external)

        completed = self.run_command("ai/.bin/install-agents", expected_code=1)

        self.assertIn("Refusing to replace linked agent", completed.stderr)
        self.assertTrue(unmanaged.is_symlink())
        self.assertEqual("Linked agent\n", external.read_text())

    def test_agent_definitions_reconcile_removed_roles(self) -> None:
        source = self.home / "agents"
        source.mkdir()
        for definition in (ROOT / "ai/agents").glob("*.md"):
            (source / definition.name).write_text(definition.read_text())
        (source / "retired.md").write_text((ROOT / "ai/agents/oracle.md").read_text())
        arguments = (
            "ai/.bin/install-agents",
            str(source),
            str(self.home / ".claude/agents"),
            str(self.home / ".omp/agent/agents"),
            str(self.home / ".config/opencode/agents"),
            str(self.home / ".codex/agents"),
            str(self.home / ".codex/config.toml"),
            str(self.home / ".pi/agent/agents"),
        )

        self.run_command(*arguments)
        unmanaged = self.home / ".claude/agents/handwritten.md"
        unmanaged.write_text("Handwritten\n")
        (source / "retired.md").unlink()
        self.run_command(*arguments)

        for retired in (
            self.home / ".claude/agents/retired.md",
            self.home / ".codex/agents/retired.toml",
            self.home / ".pi/agent/agents/retired.md",
        ):
            self.assertFalse(retired.exists())
        self.assertEqual("Handwritten\n", unmanaged.read_text())

    def test_destructive_command_guards_are_installed_idempotently(self) -> None:
        dcg = self.install_fake_dcg()
        settings = self.home / ".claude/settings.json"
        settings.parent.mkdir(parents=True)
        settings.write_text(
            json.dumps(
                {
                    "hooks": {
                        "PreToolUse": [
                            {
                                "matcher": "Read",
                                "hooks": [{"type": "command", "command": "preserve"}],
                            }
                        ]
                    }
                }
            )
        )

        self.run_command("ai/.bin/install-dcg-guards")
        self.run_command("ai/.bin/install-dcg-guards")

        entries = json.loads(settings.read_text())["hooks"]["PreToolUse"]
        commands = [entry["hooks"][0]["command"] for entry in entries]
        self.assertEqual(1, commands.count(str(dcg)))
        self.assertIn("preserve", commands)
        self.assertTrue(
            (self.home / ".config/opencode/plugins/dcg-guard.js").is_file()
        )
        self.assertTrue((self.home / ".omp/agent/extensions/dcg-guard.ts").is_file())

    def test_generated_config_is_current(self) -> None:
        self.run_command("python3", "ai/generate-config.py", "--check")
        self.run_command("ai/.bin/ai-config", "check")

    def test_pi_launcher_resolves_preset_and_forwards_arguments(self) -> None:
        fake_bin = self.home / "bin"
        fake_bin.mkdir()
        fake_pi = fake_bin / "pi"
        fake_pi.write_text("#!/bin/sh\nprintf '%s\\n' \"$@\"\n")
        fake_pi.chmod(0o755)
        self.environment["PATH"] = f"{fake_bin}:{self.environment['PATH']}"

        listed = self.run_command("ai/.bin/p", "list")
        self.assertIn(
            "fast\topenrouter/nvidia/nemotron-3.5-lightning:low\n",
            listed.stdout,
        )

        launched = self.run_command("ai/.bin/p", "fast", "--no-session", "Fix it")
        self.assertEqual(
            [
                "--model",
                "openrouter/nvidia/nemotron-3.5-lightning",
                "--thinking",
                "low",
                "--no-session",
                "Fix it",
            ],
            launched.stdout.splitlines(),
        )

        solo = self.run_command("ai/.bin/p", "solo", "--continue")
        self.assertEqual(
            [
                "--exclude-tools",
                "subagent,subagent_wait,subagent_supervisor",
                "--continue",
            ],
            solo.stdout.splitlines(),
        )

    def test_unified_profile_preflights_every_target_before_writing(self) -> None:
        pi_settings = self.home / ".pi/agent/settings.json"
        pi_settings.parent.mkdir(parents=True)
        pi_settings.write_text('{"unmanaged": true}\n')

        completed = self.run_command(
            "ai/.bin/ai-config", "use", "claude", expected_code=1
        )

        self.assertIn("refusing to overwrite unmanaged settings", completed.stderr)
        self.assertFalse((self.home / ".omp/agent/.active").exists())
        self.assertFalse((self.home / ".config/opencode/.active").exists())

    def test_profile_rendering_is_checkout_pure_and_replaces_managed_links(self) -> None:
        before = self.repository_status()
        legacy_links = {
            self.home / ".omp/agent/config.yml": ROOT / "ai/pi/config.yml",
            self.home / ".config/opencode/opencode.jsonc": ROOT
            / "ai/opencode/opencode.jsonc",
        }
        for link, target in legacy_links.items():
            link.parent.mkdir(parents=True, exist_ok=True)
            link.symlink_to(target)

        self.run_command("ai/.bin/omp-profile", "use", "codex")
        self.run_command("ai/.bin/opencode-profile", "use", "gpt")

        for path in legacy_links:
            self.assertTrue(path.is_file())
            self.assertFalse(path.is_symlink())
        self.assertEqual(before, self.repository_status())

    def test_profiles_preserve_unmanaged_config_and_state(self) -> None:
        profiles = (
            (
                "ai/.bin/omp-profile",
                "codex",
                self.home / ".omp/agent/config.yml",
                self.home / ".omp/agent/.active",
            ),
            (
                "ai/.bin/opencode-profile",
                "gpt",
                self.home / ".config/opencode/opencode.jsonc",
                self.home / ".config/opencode/.active",
            ),
            (
                "ai/.bin/pi-profile",
                "codex",
                self.home / ".pi/agent/settings.json",
                self.home / ".pi/agent/.active-profile",
            ),
        )

        for script, profile, config, active in profiles:
            with self.subTest(script=script, target="config"):
                config.parent.mkdir(parents=True, exist_ok=True)
                config.write_text("unmanaged configuration\n")
                completed = self.run_command(script, "use", profile, expected_code=1)
                self.assertIn("refusing to overwrite unmanaged", completed.stderr)
                self.assertEqual("unmanaged configuration\n", config.read_text())
                config.unlink()

            with self.subTest(script=script, target="state"):
                external = self.home / f"{profile}-{Path(script).name}-state"
                external.write_text("user state\n")
                active.symlink_to(external)
                completed = self.run_command(script, "use", profile, expected_code=1)
                self.assertIn("refusing to overwrite unmanaged", completed.stderr)
                self.assertTrue(active.is_symlink())
                self.assertEqual("user state\n", external.read_text())
                active.unlink()

    def test_ai_tool_selection_defaults_to_none_and_rejects_unknown_values(
        self,
    ) -> None:
        self.environment.pop("DOTFILES_AI_TOOLS")
        listed = self.run_command("ai/.bin/ai-tool-enabled", "--list")
        self.assertEqual("", listed.stdout)

        self.environment["DOTFILES_AI_TOOLS"] = "pi,wat"
        completed = self.run_command(
            "ai/.bin/ai-tool-enabled", "--validate", expected_code=2
        )
        self.assertIn("unknown tool: wat", completed.stderr)

    def test_ai_tool_configuration_refuses_dangling_managed_paths(self) -> None:
        config = self.home / ".config/mise/conf.d/40-ai.toml"
        config.parent.mkdir(parents=True)
        external = self.home / "missing-ai.toml"
        config.symlink_to(external)
        self.install_fake_mise()

        completed = self.run_command("ai/.bin/configure-ai-tools", expected_code=1)

        self.assertIn("Refusing to overwrite linked AI Mise config", completed.stderr)
        self.assertFalse(external.exists())

    def test_disabled_codex_preserves_unmanaged_config(self) -> None:
        self.environment["DOTFILES_AI_TOOLS"] = "none"
        config = self.home / ".codex/config.toml"
        config.parent.mkdir(parents=True)
        config.write_text("unmanaged = true\n")

        self.run_command("ai/.bin/install-agents")

        self.assertEqual("unmanaged = true\n", config.read_text())

    def test_pi_only_selection_installs_pi_and_uninstalls_other_ai_tools(self) -> None:
        log = self.install_fake_mise()
        self.run_command("ai/.bin/configure-ai-tools")
        log.write_text("")
        self.environment["DOTFILES_AI_TOOLS"] = "pi"

        self.run_command("ai/.bin/configure-ai-tools")

        config = self.home / ".config/mise/conf.d/40-ai.toml"
        text = config.read_text()
        self.assertIn("npm:@earendil-works/pi-coding-agent", text)
        self.assertIn("github:Dicklesworthstone/destructive_command_guard", text)
        self.assertNotIn("@anthropic-ai/claude-code", text)
        commands = log.read_text().splitlines()
        self.assertIn(
            "install --yes github:Dicklesworthstone/destructive_command_guard npm:@earendil-works/pi-coding-agent",
            commands,
        )
        self.assertTrue(
            any(line.startswith("uninstall --all --yes ") for line in commands)
        )

        self.run_command("ai/.bin/install-agents")
        self.assertTrue((self.home / ".pi/agent/agents/explore.md").is_file())
        self.assertFalse((self.home / ".claude/agents/executor.md").exists())
        self.assertFalse((self.home / ".codex/agents/executor.toml").exists())

    def test_make_ai_is_idempotent_and_checkout_pure(self) -> None:
        before = self.repository_status()
        self.install_fake_mise()
        self.install_fake_dcg()
        repository_envrc = ROOT / "base/.envrc"
        if not (repository_envrc.exists() or repository_envrc.is_symlink()):
            local_envrc = self.home / ".envrc"
            local_envrc.write_text("\n")
            repository_envrc.symlink_to(local_envrc)
            self.addCleanup(repository_envrc.unlink)

        self.run_command("make", "ai")
        self.run_command("make", "ai")

        self.assertEqual(before, self.repository_status())
        for path in (
            self.home / ".claude/agents/executor.md",
            self.home / ".omp/agent/agents/explore.md",
            self.home / ".pi/agent/agents/explore.md",
            self.home / ".config/opencode/agents/explore.md",
            self.home / ".codex/agents/executor.toml",
        ):
            self.assertTrue(path.is_file(), path)

        self.environment["DOTFILES_AI_TOOLS"] = "pi"
        self.run_command("make", "ai")
        self.assertTrue((self.home / ".pi/agent/AGENTS.md").is_symlink())
        self.assertFalse((self.home / ".claude/CLAUDE.md").exists())
        self.assertFalse((self.home / ".claude/agents/executor.md").exists())
        self.assertFalse((self.home / ".codex/agents/executor.toml").exists())
        self.assertEqual(before, self.repository_status())


if __name__ == "__main__":
    unittest.main()
