from __future__ import annotations

import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[2]


class AiInstallTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.home = Path(self.temporary.name)
        self.environment = {
            **os.environ,
            "DOTFILES": str(ROOT),
            "HOME": str(self.home),
        }

    def run_command(
        self, *arguments: str, expected_code: int = 0
    ) -> subprocess.CompletedProcess[str]:
        completed = subprocess.run(
            arguments,
            text=True,
            capture_output=True,
            cwd=ROOT,
            env=self.environment,
            check=False,
        )
        self.assertEqual(
            expected_code, completed.returncode, completed.stderr or completed.stdout
        )
        return completed

    def repository_status(self) -> str:
        completed = subprocess.run(
            ["git", "status", "--porcelain"],
            text=True,
            capture_output=True,
            cwd=ROOT,
            check=False,
        )
        self.assertEqual(0, completed.returncode, completed.stderr)
        return completed.stdout

    def load_yaml(self, text: str) -> object:
        yaml_path = str(ROOT / "dotbot/lib/pyyaml/lib")
        sys.path.insert(0, yaml_path)
        try:
            import yaml

            return yaml.safe_load(text)
        finally:
            sys.path.remove(yaml_path)

    def test_command_adapters_are_generated_without_duplicate_claude_commands(
        self,
    ) -> None:
        before = self.repository_status()
        legacy_command = self.home / ".claude/commands/pr-review-draft.md"
        unmanaged_command = self.home / ".claude/commands/manual.md"
        legacy_command.parent.mkdir(parents=True)
        legacy_command.write_text(
            "---\ndescription: legacy\n---\n\n"
            "<!-- Generated by install-agent-commands. -->\n"
        )
        unmanaged_command.write_text("Unmanaged command\n")
        unmanaged_opencode_command = (
            self.home / ".config/opencode/commands/manual.md"
        )
        unmanaged_opencode_command.parent.mkdir(parents=True)
        unmanaged_opencode_command.write_text("Unmanaged OpenCode command\n")

        self.run_command("ai/.bin/install-agent-commands")

        generated_skill = self.home / ".agents/skills/pr-review-draft/SKILL.md"
        claude_skill = self.home / ".claude/skills/pr-review-draft/SKILL.md"
        self.assertIn("Generated by install-agent-commands.", generated_skill.read_text())
        self.assertIn("argument-hint: <pr-number|url>", generated_skill.read_text())
        self.assertEqual(generated_skill.read_text(), claude_skill.read_text())
        self.assertTrue(
            (self.home / ".agents/skills/pr-review-draft/agents/openai.yaml").is_file()
        )
        opencode_command = (
            self.home / ".config/opencode/commands/pr-review-draft.md"
        )
        self.assertIn(
            "Generated by install-agent-commands.", opencode_command.read_text()
        )
        self.assertIn("Review PR `$ARGUMENTS` read-only", opencode_command.read_text())
        self.assertFalse(legacy_command.exists())
        self.assertEqual("Unmanaged command\n", unmanaged_command.read_text())
        self.assertEqual(
            "Unmanaged OpenCode command\n", unmanaged_opencode_command.read_text()
        )
        self.assertEqual(before, self.repository_status())

    def test_generated_skill_frontmatter_is_valid_yaml(self) -> None:
        self.run_command("ai/.bin/install-agent-commands")

        for skill in (self.home / ".agents/skills").glob("*/SKILL.md"):
            with self.subTest(skill=skill):
                text = skill.read_text()
                self.assertTrue(text.startswith("---\n"))
                frontmatter = text.split("---\n", 2)[1]
                metadata = self.load_yaml(frontmatter)
                self.assertIsInstance(metadata, dict)
                self.assertEqual(skill.parent.name, metadata["name"])

    def test_remote_mutation_authority_stays_explicit(self) -> None:
        self.run_command("ai/.bin/install-agent-commands")

        implement = (
            self.home / ".agents/skills/implement/SKILL.md"
        ).read_text()
        backlog = (
            ROOT / "ai/.agents/skills/backlog-source-workflow/SKILL.md"
        ).read_text()
        agents = (ROOT / "ai/AGENTS.md").read_text()

        self.assertIn("Never infer permission to push or open a PR", implement)
        self.assertIn("calling command supplies intent and mutation authority", backlog)
        self.assertIn("actively prompt the user in the current session", agents)

    def test_external_messages_route_through_writer(self) -> None:
        agents = (ROOT / "ai/AGENTS.md").read_text()
        draft = (ROOT / "ai/.agents/skills/draft-in-editor/SKILL.md").read_text()

        self.assertIn("Delegate externally directed wording to `writer`", agents)
        self.assertIn("$HOME/.bin/context-editor --no-terminal", draft)
        self.assertIn("reread the file immediately beforehand", draft)

    def test_ralph_loop_does_not_request_interactive_human_input(self) -> None:
        self.run_command("ai/.bin/install-agent-commands")

        generated_skill = (
            self.home / ".agents/skills/backlog-implement-review-loop/SKILL.md"
        )
        self.assertNotIn("question or user-input tool", generated_skill.read_text())


    def test_command_adapters_preserve_unmanaged_skill_files(self) -> None:
        skill_dir = self.home / ".agents/skills/pr-review-draft"
        skill = skill_dir / "SKILL.md"
        skill_dir.mkdir(parents=True)
        skill.write_text("Unmanaged skill\n")

        completed = self.run_command(
            "ai/.bin/install-agent-commands", expected_code=1
        )

        self.assertIn("Refusing to overwrite unmanaged skill", completed.stderr)
        self.assertEqual("Unmanaged skill\n", skill.read_text())

    def test_command_adapters_preserve_unmanaged_skill_links(self) -> None:
        skill_dir = self.home / ".agents/skills/pr-review-draft"
        skill_dir.parent.mkdir(parents=True)
        skill_dir.symlink_to(self.home / "external-skill")

        completed = self.run_command(
            "ai/.bin/install-agent-commands", expected_code=1
        )

        self.assertIn("Refusing to replace linked skill directory", completed.stderr)
        self.assertTrue(skill_dir.is_symlink())

    def agent_body(self, path: Path) -> str:
        _, _, remainder = path.read_text().partition("---\n")
        _, _, body = remainder.partition("\n---\n")
        return body.lstrip("\n")

    def test_agent_definitions_are_generated_in_home(self) -> None:
        before = self.repository_status()

        self.run_command("ai/.bin/install-agents")

        claude = self.home / ".claude/agents/executor.md"
        omp = self.home / ".omp/agent/agents/executor.md"
        pi = self.home / ".pi/agent/agents/executor.md"
        opencode = self.home / ".config/opencode/agents/executor.md"
        codex = self.home / ".codex/agents/executor.toml"
        self.assertIn("model: sonnet", claude.read_text())
        self.assertIn("model: pi/task", omp.read_text())
        self.assertIn("name: executor", pi.read_text())
        self.assertNotIn("model:", pi.read_text())
        self.assertIn("mode: subagent", opencode.read_text())
        self.assertIn('model = "gpt-5.6-luna"', codex.read_text())
        self.assertIn(
            "model: claude-opus-4-8",
            (self.home / ".claude/agents/reviewer.md").read_text(),
        )
        self.assertIn(
            "model: pi/reviewer",
            (self.home / ".omp/agent/agents/reviewer.md").read_text(),
        )
        self.assertTrue((self.home / ".pi/agent/agents/reviewer.md").is_file())
        self.assertTrue(
            (self.home / ".config/opencode/agents/reviewer.md").is_file()
        )
        self.assertIn(
            'model = "gpt-5.6-terra"',
            (self.home / ".codex/agents/reviewer.toml").read_text(),
        )
        self.assertIn(
            "model: sonnet", (self.home / ".claude/agents/writer.md").read_text()
        )
        self.assertIn(
            "model: pi/writer",
            (self.home / ".omp/agent/agents/writer.md").read_text(),
        )
        self.assertTrue((self.home / ".pi/agent/agents/writer.md").is_file())
        self.assertTrue(
            (self.home / ".config/opencode/agents/writer.md").is_file()
        )
        self.assertIn(
            'model = "gpt-5.6-terra"',
            (self.home / ".codex/agents/writer.toml").read_text(),
        )
        self.assertIn(
            "config_file", (self.home / ".codex/config.toml").read_text()
        )
        self.assertIn(
            "Generated by install-agents.",
            (self.home / ".claude/agents/.install-agents").read_text(),
        )
        self.assertEqual(before, self.repository_status())

    def test_agent_definitions_retire_legacy_omp_directory(self) -> None:
        legacy = self.home / ".omp/agents"
        legacy.mkdir(parents=True)
        (legacy / ".install-agents").write_text(
            "# Generated by install-agents.\nexecutor.md\n"
        )
        (legacy / "executor.md").write_text("Generated\n")
        (legacy / "handwritten.md").write_text("Handwritten\n")

        self.run_command("ai/.bin/install-agents")

        self.assertFalse((legacy / "executor.md").exists())
        self.assertFalse((legacy / ".install-agents").exists())
        self.assertEqual("Handwritten\n", (legacy / "handwritten.md").read_text())

    def test_legacy_omp_retirement_preserves_untrusted_and_linked_files(
        self,
    ) -> None:
        legacy = self.home / ".omp/agents"
        legacy.mkdir(parents=True)
        manifest = legacy / ".install-agents"
        generated = legacy / "executor.md"
        external = self.home / "external-agent.md"
        linked = legacy / "linked.md"
        manifest.write_text("User manifest\nexecutor.md\nlinked.md\n")
        generated.write_text("User file\n")
        external.write_text("External\n")
        linked.symlink_to(external)

        self.run_command("ai/.bin/install-agents")

        self.assertEqual("User file\n", generated.read_text())
        self.assertTrue(linked.is_symlink())
        self.assertEqual("User manifest\nexecutor.md\nlinked.md\n", manifest.read_text())

        manifest.write_text("# Generated by install-agents.\n.\nlinked.md\n")
        self.run_command("ai/.bin/install-agents")

        self.assertFalse(manifest.exists())
        self.assertTrue(linked.is_symlink())
        self.assertEqual("External\n", external.read_text())
        self.assertEqual("User file\n", generated.read_text())

    def test_legacy_omp_retirement_preserves_symlinked_ownership_state(
        self,
    ) -> None:
        legacy = self.home / ".omp/agents"
        external = self.home / "external-agents"
        external.mkdir(parents=True)
        external_manifest = external / ".install-agents"
        external_file = external / "executor.md"
        external_manifest.write_text(
            "# Generated by install-agents.\nexecutor.md\n"
        )
        external_file.write_text("External\n")
        legacy.parent.mkdir(parents=True)
        legacy.symlink_to(external, target_is_directory=True)

        self.run_command("ai/.bin/install-agents")

        self.assertTrue(legacy.is_symlink())
        self.assertEqual("External\n", external_file.read_text())
        legacy.unlink()

        legacy.mkdir()
        local_file = legacy / "executor.md"
        local_file.write_text("Local\n")
        (legacy / ".install-agents").symlink_to(external_manifest)

        self.run_command("ai/.bin/install-agents")

        self.assertEqual("Local\n", local_file.read_text())
        self.assertTrue((legacy / ".install-agents").is_symlink())

    def test_agent_definitions_preserve_linked_active_manifest(self) -> None:
        agents = self.home / ".omp/agent/agents"
        agents.mkdir(parents=True)
        external = self.home / "external-manifest"
        external.write_text("# Generated by install-agents.\nexternal.md\n")
        manifest = agents / ".install-agents"
        manifest.symlink_to(external)

        completed = self.run_command("ai/.bin/install-agents", expected_code=1)

        self.assertIn("Refusing to replace linked agent manifest", completed.stderr)
        self.assertEqual(
            "# Generated by install-agents.\nexternal.md\n",
            external.read_text(),
        )
        self.assertTrue(manifest.is_symlink())

    def test_agent_definitions_preserve_unmanaged_active_manifest(self) -> None:
        agents = self.home / ".omp/agent/agents"
        agents.mkdir(parents=True)
        manifest = agents / ".install-agents"
        manifest.write_text("User manifest\n")

        completed = self.run_command("ai/.bin/install-agents", expected_code=1)

        self.assertIn(
            "Refusing to overwrite unmanaged agent manifest", completed.stderr
        )
        self.assertEqual("User manifest\n", manifest.read_text())

    def test_agent_reconciliation_ignores_unsafe_manifest_entries(self) -> None:
        agents = self.home / ".omp/agent/agents"
        agents.mkdir(parents=True)
        external = self.home / "external-agent.md"
        external.write_text("External\n")
        linked = agents / "linked.md"
        linked.symlink_to(external)
        (agents / ".install-agents").write_text(
            "# Generated by install-agents.\n"
            "../../../../external-agent.md\n"
            ".\n"
            "linked.md\n"
        )

        self.run_command("ai/.bin/install-agents")

        self.assertEqual("External\n", external.read_text())
        self.assertTrue(linked.is_symlink())

    def test_agent_definitions_preserve_linked_output_paths(self) -> None:
        agents = self.home / ".claude/agents"
        external_agents = self.home / "external-agents"
        external_agents.mkdir()
        agents.parent.mkdir(parents=True)
        agents.symlink_to(external_agents, target_is_directory=True)

        completed = self.run_command("ai/.bin/install-agents", expected_code=1)

        self.assertIn("Refusing to use linked agent directory", completed.stderr)
        self.assertEqual([], list(external_agents.iterdir()))
        agents.unlink()

        codex_config = self.home / ".codex/config.toml"
        codex_config.parent.mkdir(parents=True)
        external_config = self.home / "external-codex-config.toml"
        external_config.write_text("User config\n")
        codex_config.symlink_to(external_config)

        completed = self.run_command("ai/.bin/install-agents", expected_code=1)

        self.assertIn("Refusing to replace linked Codex config", completed.stderr)
        self.assertEqual("User config\n", external_config.read_text())

    def test_agent_definitions_preserve_codex_hook_trust_state(self) -> None:
        config = self.home / ".codex/config.toml"
        config.parent.mkdir()
        config.write_text(
            """[features]
hooks = true

# BEGIN generated Codex agents

[agents.executor]
description = "obsolete"
config_file = "/tmp/obsolete.toml"

[hooks.state]

[hooks.state."/Users/brett/.codex/hooks.json:session_start:0:0"]
trusted_hash = "sha256:trusted"
# END generated Codex agents
"""
        )

        self.run_command("ai/.bin/install-agents")

        rendered = config.read_text()
        self.assertIn('trusted_hash = "sha256:trusted"', rendered)
        self.assertLess(
            rendered.index("[hooks.state]"),
            rendered.index("# BEGIN generated Codex agents"),
        )
        self.assertNotIn('description = "obsolete"', rendered)

    def test_agent_definitions_share_one_body_across_tools(self) -> None:
        self.run_command("ai/.bin/install-agents")

        for role in (
            "reviewer",
            "executor",
            "verifier",
            "pr-watcher",
            "oracle",
            "writer",
        ):
            claude = self.agent_body(self.home / f".claude/agents/{role}.md")
            omp = self.agent_body(self.home / f".omp/agent/agents/{role}.md")
            pi = self.agent_body(self.home / f".pi/agent/agents/{role}.md")
            opencode = self.agent_body(
                self.home / f".config/opencode/agents/{role}.md"
            )
            self.assertEqual(claude, omp, role)
            self.assertEqual(claude, pi, role)
            self.assertEqual(claude, opencode, role)

        # Claude ships neither of these; it uses its built-in Explore and loads
        # the review skill directly.
        for role in ("explore", "thermo-nuclear-code-quality-review"):
            self.assertFalse((self.home / f".claude/agents/{role}.md").exists())
            self.assertTrue(
                (self.home / f".omp/agent/agents/{role}.md").is_file()
            )
            self.assertTrue(
                (self.home / f".pi/agent/agents/{role}.md").is_file()
            )
            self.assertFalse((self.home / f".codex/agents/{role}.toml").exists())

    def test_agent_definitions_preserve_unmanaged_targets(self) -> None:
        agents_dir = self.home / ".claude/agents"
        agents_dir.mkdir(parents=True)
        unmanaged = agents_dir / "oracle.md"
        unmanaged.write_text("Unmanaged agent\n")

        completed = self.run_command("ai/.bin/install-agents", expected_code=1)

        self.assertIn("Refusing to overwrite unmanaged agent", completed.stderr)
        self.assertEqual("Unmanaged agent\n", unmanaged.read_text())

        unmanaged.unlink()
        external = self.home / "external-agent.md"
        external.write_text("Linked agent\n")
        unmanaged.symlink_to(external)

        completed = self.run_command("ai/.bin/install-agents", expected_code=1)

        self.assertIn("Refusing to replace linked agent", completed.stderr)
        self.assertTrue(unmanaged.is_symlink())

    def test_agent_definitions_reap_removed_roles(self) -> None:
        source = self.home / "agents"
        source.mkdir()
        for definition in (ROOT / "ai/agents").glob("*.md"):
            (source / definition.name).write_text(definition.read_text())
        (source / "retired.md").write_text(
            (ROOT / "ai/agents/oracle.md").read_text()
        )
        arguments = (
            "ai/.bin/install-agents",
            str(source),
            str(self.home / ".claude/agents"),
            str(self.home / ".omp/agent/agents"),
            str(self.home / ".config/opencode/agents"),
            str(self.home / ".codex/agents"),
            str(self.home / ".codex/config.toml"),
            str(self.home / ".pi/agent/agents"),
        )

        self.run_command(*arguments)
        retired = self.home / ".claude/agents/retired.md"
        unmanaged = self.home / ".claude/agents/handwritten.md"
        unmanaged.write_text("Handwritten\n")
        self.assertTrue(retired.is_file())

        (source / "retired.md").unlink()
        self.run_command(*arguments)

        self.assertFalse(retired.exists())
        self.assertFalse((self.home / ".codex/agents/retired.toml").exists())
        self.assertFalse(
            (self.home / ".pi/agent/agents/retired.md").exists()
        )
        self.assertNotIn("retired", (self.home / ".codex/config.toml").read_text())
        self.assertEqual("Handwritten\n", unmanaged.read_text())

    def test_model_limits_are_managed_by_ai_install(self) -> None:
        installer = (ROOT / "ai.yaml").read_text()
        omp_models = self.load_yaml((ROOT / "ai/omp/models.yml").read_text())
        pi_models = json.loads((ROOT / "ai/pi/models.json").read_text())

        self.assertIn("~/.omp/agent/models.yml:", installer)
        self.assertIn("path: ai/omp/models.yml", installer)
        expected_codex = {
            "gpt-5.6-luna": {"contextWindow": 272000},
            "gpt-5.6-sol": {"contextWindow": 272000},
            "gpt-5.6-terra": {"contextWindow": 272000},
        }
        self.assertEqual(
            expected_codex,
            omp_models["providers"]["openai-codex"]["modelOverrides"],
        )
        openrouter_overrides = omp_models["providers"]["openrouter"][
            "modelOverrides"
        ]
        codex_openrouter_models = {f"openai/{name}" for name in expected_codex}
        for model, override in openrouter_overrides.items():
            expected = 272000 if model in codex_openrouter_models else 256000
            self.assertEqual({"contextWindow": expected}, override, model)
        for model, override in omp_models["providers"]["anthropic"][
            "modelOverrides"
        ].items():
            self.assertEqual({"contextWindow": 256000}, override, model)
        self.assertEqual(
            expected_codex,
            pi_models["providers"]["openai-codex"]["modelOverrides"],
        )
        expected_pi_openrouter = {
            "anthropic/claude-fable-latest": {"contextWindow": 256000},
            "anthropic/claude-opus-4.6": {"contextWindow": 256000},
            "anthropic/claude-opus-4.8": {"contextWindow": 256000},
            "openai/gpt-5.6-luna": {"contextWindow": 272000},
            "openai/gpt-5.6-sol": {"contextWindow": 272000},
            "openai/gpt-5.6-sol-pro": {"contextWindow": 272000},
            "z-ai/glm-5.3": {"contextWindow": 256000},
            "~anthropic/claude-fable-latest": {"contextWindow": 256000},
        }
        self.assertEqual(
            expected_pi_openrouter,
            pi_models["providers"]["openrouter"]["modelOverrides"],
        )

        pi_openrouter_profile = json.loads(
            (ROOT / "ai/pi/profiles/or.json").read_text()
        )
        profile_models = set(pi_openrouter_profile["enabledModels"])
        profile_models.add(pi_openrouter_profile["defaultModel"])
        subagents = pi_openrouter_profile["subagents"]
        profile_models.add(
            subagents["defaultModel"].removeprefix("openrouter/")
        )
        profile_models.update(
            override["model"].removeprefix("openrouter/")
            for override in subagents["agentOverrides"].values()
        )
        self.assertLessEqual(profile_models, set(expected_pi_openrouter))
        self.run_command(
            "dotbot/bin/dotbot",
            "-d",
            str(ROOT),
            "-c",
            "ai.yaml",
            "--only",
            "link",
        )
        installed = self.home / ".omp/agent/models.yml"
        self.assertTrue(installed.is_symlink())
        self.assertEqual((ROOT / "ai/omp/models.yml").resolve(), installed.resolve())
        pi_installed = self.home / ".pi/agent/models.json"
        self.assertTrue(pi_installed.is_symlink())
        self.assertEqual((ROOT / "ai/pi/models.json").resolve(), pi_installed.resolve())
        pi_keybindings = self.home / ".pi/agent/keybindings.json"
        self.assertTrue(pi_keybindings.is_symlink())
        self.assertEqual(
            (ROOT / "ai/pi/keybindings.json").resolve(), pi_keybindings.resolve()
        )
        bindings = json.loads(pi_keybindings.read_text())
        self.assertEqual(["up", "ctrl+p"], bindings["tui.editor.cursorUp"])
        self.assertEqual(["down", "ctrl+n"], bindings["tui.editor.cursorDown"])
        self.assertEqual(["up", "ctrl+p"], bindings["tui.select.up"])
        self.assertEqual(["down", "ctrl+n"], bindings["tui.select.down"])
        self.assertEqual(
            ["shift+enter", "ctrl+j", "alt+enter"],
            bindings["tui.input.newLine"],
        )
        self.assertEqual("ctrl+q", bindings["app.message.followUp"])
        self.assertEqual("alt+p", bindings["app.model.select"])
        self.assertEqual([], bindings["app.model.cycleForward"])
        watchdog = self.home / ".omp/agent/WATCHDOG.md"
        self.assertTrue(watchdog.is_symlink())
        self.assertEqual((ROOT / "ai/WATCHDOG.md").resolve(), watchdog.resolve())
        mcp = self.home / ".omp/agent/mcp.json"
        self.assertTrue(mcp.is_symlink())
        self.assertEqual((ROOT / "ai/omp/mcp.json").resolve(), mcp.resolve())
        self.assertIn('"context7"', mcp.read_text())
        omp_agents = self.home / ".omp/agent/AGENTS.md"
        self.assertTrue(omp_agents.is_symlink())
        self.assertEqual((ROOT / "ai/AGENTS.md").resolve(), omp_agents.resolve())
        pi_agents = self.home / ".pi/agent/AGENTS.md"
        self.assertTrue(pi_agents.is_symlink())
        self.assertEqual((ROOT / "ai/AGENTS.md").resolve(), pi_agents.resolve())
        mise = (
            ROOT / "darwin/.config/mise/conf.d/50-darwin.toml"
        ).read_text()
        self.assertIn("npm:@earendil-works/pi-coding-agent", mise)

    def test_omp_profiles_select_their_available_search_provider(self) -> None:
        config = self.home / ".omp/agent/config.yml"

        self.run_command("ai/.bin/omp-profile", "use", "codex")
        self.assertIn(
            "providers:\n  webSearchOrder:\n  - codex\n", config.read_text()
        )

        self.run_command("ai/.bin/omp-profile", "use", "or")
        self.assertIn(
            "providers:\n  webSearchOrder:\n  - perplexity\n", config.read_text()
        )

    def test_pi_codex_profile_merges_minimal_ui_and_tooling(self) -> None:
        before = self.repository_status()

        self.run_command("ai/.bin/pi-profile", "use", "codex")

        settings_path = self.home / ".pi/agent/settings.json"
        settings = json.loads(settings_path.read_text())
        self.assertEqual("openai-codex", settings["defaultProvider"])
        self.assertEqual("gpt-5.6-sol", settings["defaultModel"])
        self.assertEqual("medium", settings["defaultThinkingLevel"])
        self.assertEqual(
            ["gpt-5.6-luna", "gpt-5.6-sol", "gpt-5.6-terra"],
            settings["enabledModels"],
        )
        self.assertTrue(settings["quietStartup"])
        self.assertEqual("all", settings["steeringMode"])
        self.assertTrue(settings["hideThinkingBlock"])
        self.assertEqual("dark", settings["theme"])
        self.assertEqual(0, settings["outputPad"])
        self.assertEqual(0, settings["editorPaddingX"])
        self.assertEqual(
            [
                "npm:pi-subagents@0.60.0",
                "npm:pi-lsp-adapter@0.1.3",
                "npm:pi-web-access@0.27.0",
                "npm:pi-mcp-adapter@2.32.1",
                "../../dev/me/pi-live-codex",
                "npm:pi-chrome@0.15.46",
                "npm:@sting8k/pi-vcc@0.7.0",
            ],
            settings["packages"],
        )
        self.assertEqual(
            {
                "searchRouting": {
                    "providers": ["openai"],
                    "useCurrentModel": True,
                    "fallbackOn": [
                        "unsupported",
                        "transient",
                        "quota",
                        "network",
                        "invalid-response",
                    ],
                }
            },
            json.loads((self.home / ".pi/web-search.json").read_text()),
        )
        vcc_config = json.loads(
            (self.home / ".pi/agent/pi-vcc-config.json").read_text()
        )
        self.assertEqual(
            {
                "overrideDefaultCompaction": True,
                "smartKeepTail": True,
                "continueAfterThresholdCompact": False,
                "debug": False,
            },
            vcc_config,
        )
        subagents = settings["subagents"]
        self.assertEqual("openai-codex", subagents["defaultProvider"])
        self.assertEqual(
            {
                "enforce": True,
                "strict": True,
                "allow": ["openai-codex/gpt-5.6-*"],
            },
            subagents["modelScope"],
        )
        reviewer = settings["subagents"]["agentOverrides"]["reviewer"]
        self.assertEqual("openai-codex/gpt-5.6-terra", reviewer["model"])
        self.assertEqual("max", reviewer["thinking"])
        self.assertEqual(
            "codex\n", (self.home / ".pi/agent/.active-profile").read_text()
        )
        self.assertEqual(before, self.repository_status())

    def test_pi_openrouter_profile_routes_parent_and_subagents(self) -> None:
        before = self.repository_status()

        self.run_command("ai/.bin/pi-profile", "use", "codex")
        completed = self.run_command("ai/.bin/pi-profile", "use", "or")
        self.assertEqual("switched to or\n", completed.stdout)

        settings = json.loads((self.home / ".pi/agent/settings.json").read_text())
        self.assertEqual("openrouter", settings["defaultProvider"])
        self.assertEqual("openai/gpt-5.6-sol", settings["defaultModel"])
        self.assertEqual("medium", settings["defaultThinkingLevel"])
        self.assertEqual(
            [str(ROOT / "ai/pi/extensions/openrouter-web-search.ts")],
            settings["extensions"],
        )
        self.assertEqual(
            {"tools": {"webSearch": {"enabled": False}}},
            json.loads((self.home / ".pi/web-search.json").read_text()),
        )
        subagents = settings["subagents"]
        self.assertEqual("openrouter", subagents["defaultProvider"])
        self.assertEqual(
            "openrouter/openai/gpt-5.6-luna", subagents["defaultModel"]
        )
        overrides = subagents["agentOverrides"]
        self.assertEqual(
            {
                "model": "openrouter/anthropic/claude-opus-4.8",
                "thinking": "xhigh",
            },
            overrides["reviewer"],
        )
        self.assertEqual(
            {
                "model": "openrouter/anthropic/claude-opus-4.6",
                "thinking": "medium",
            },
            overrides["writer"],
        )
        self.assertEqual(
            "or\n", (self.home / ".pi/agent/.active-profile").read_text()
        )
        self.assertEqual(before, self.repository_status())

    def test_pi_profile_preserves_unmanaged_settings_and_state(self) -> None:
        settings = self.home / ".pi/agent/settings.json"
        settings.parent.mkdir(parents=True)
        settings.write_text('{"user": true}\n')

        completed = self.run_command(
            "ai/.bin/pi-profile", "use", "codex", expected_code=1
        )

        self.assertIn("refusing to overwrite unmanaged settings", completed.stderr)
        self.assertEqual('{"user": true}\n', settings.read_text())
        settings.unlink()

        active = self.home / ".pi/agent/.active-profile"
        external = self.home / "pi-active-profile"
        external.write_text("user state\n")
        active.symlink_to(external)
        completed = self.run_command(
            "ai/.bin/pi-profile", "use", "codex", expected_code=1
        )
        self.assertIn(
            "refusing to overwrite unmanaged active profile", completed.stderr
        )
        self.assertEqual("user state\n", external.read_text())

    def test_profile_rendering_writes_only_home(self) -> None:
        before = self.repository_status()
        legacy_links = {
            self.home / ".omp/agent/config.yml": ROOT / "ai/pi/config.yml",
            self.home / ".config/opencode/opencode.jsonc": ROOT
            / "ai/opencode/opencode.jsonc",
        }
        for link, target in legacy_links.items():
            link.parent.mkdir(parents=True, exist_ok=True)
            link.symlink_to(target)


        self.run_command("ai/.bin/omp-profile", "use", "codex")
        self.run_command("ai/.bin/opencode-profile", "use", "gpt")

        omp_config = self.home / ".omp/agent/config.yml"
        opencode_config = self.home / ".config/opencode/opencode.jsonc"
        self.assertIn("ai/omp/profiles/codex.yml", omp_config.read_text())
        self.assertIn("ai/opencode/profiles/gpt.jsonc", opencode_config.read_text())
        self.assertIn(
            "reviewer: openai-codex/gpt-5.6-terra:max",
            omp_config.read_text(),
        )
        self.assertIn("thresholdPercent: -1", omp_config.read_text())
        self.assertIn('"reviewer"', opencode_config.read_text())
        self.assertIn(
            "writer: openai-codex/gpt-5.6-terra:low", omp_config.read_text()
        )
        self.assertIn('"writer"', opencode_config.read_text())
        self.assertIn('"model": "openai/gpt-5.6-terra"', opencode_config.read_text())
        self.assertIn('"context": 256000', opencode_config.read_text())
        self.assertIn('"input": 128000', opencode_config.read_text())
        self.assertIn('"output": 128000', opencode_config.read_text())
        self.assertEqual("codex\n", (self.home / ".omp/agent/.active").read_text())
        self.assertEqual("gpt\n", (self.home / ".config/opencode/.active").read_text())
        self.assertEqual(before, self.repository_status())
        self.assertFalse(omp_config.is_symlink())
        self.assertFalse(opencode_config.is_symlink())

    def test_openrouter_cheap_profiles_preserve_original_routes(self) -> None:
        self.run_command("ai/.bin/omp-profile", "use", "or")
        self.run_command("ai/.bin/opencode-profile", "use", "or")

        pi_config_path = self.home / ".omp/agent/config.yml"
        opencode_config_path = self.home / ".config/opencode/opencode.jsonc"
        self.assertIn(
            "default: openrouter/openai/gpt-5.6-sol:medium",
            pi_config_path.read_text(),
        )
        self.assertIn(
            '"model": "openrouter/openai/gpt-5.6-terra"',
            opencode_config_path.read_text(),
        )

        self.run_command("ai/.bin/omp-profile", "use", "or-cheap")
        self.run_command("ai/.bin/opencode-profile", "use", "or-cheap")

        pi_config = pi_config_path.read_text()
        self.assertIn(
            "default: openrouter/deepseek/deepseek-v4-pro-0813:high",
            pi_config,
        )
        self.assertIn("slow: openrouter/z-ai/glm-5.3:max", pi_config)
        self.assertIn(
            "commit: openrouter/~deepseek/deepseek-v4-flash-latest:low",
            pi_config,
        )
        self.assertIn(
            "vision: openrouter/deepseek/deepseek-v4-flash-vision-exp:high",
            pi_config,
        )

        opencode_text = opencode_config_path.read_text()
        opencode_config = json.loads(
            "\n".join(
                line
                for line in opencode_text.splitlines()
                if not line.startswith("//")
            )
        )
        agents = opencode_config["agent"]
        self.assertEqual(
            {
                "model": "openrouter/deepseek/deepseek-v4-pro-0813",
                "variant": "max",
            },
            agents["executor"],
        )
        self.assertEqual(
            {"model": "openrouter/z-ai/glm-5.3", "variant": "max"},
            agents["reviewer"],
        )
        self.assertEqual(
            {
                "model": "openrouter/~deepseek/deepseek-v4-flash-latest",
                "variant": "low",
            },
            agents["explore"],
        )
        self.assertEqual(
            {
                "model": "openrouter/deepseek/deepseek-v4-pro-0813",
                "variant": "max",
            },
            agents["verifier"],
        )

    def test_omp_profile_accepts_rewritten_managed_config(self) -> None:
        self.run_command("ai/.bin/omp-profile", "use", "codex")
        config = self.home / ".omp/agent/config.yml"
        without_comments = "\n".join(
            line for line in config.read_text().splitlines() if not line.startswith("#")
        )
        config.write_text(f"{without_comments}\ndev:\n  autoqaConsent: denied\n")

        self.run_command("ai/.bin/omp-profile", "use", "codex")

        rendered = config.read_text()
        self.assertTrue(rendered.startswith("# Generated by omp-profile"))
        self.assertNotIn("autoqaConsent", rendered)

    def test_profiles_preserve_unmanaged_local_config_and_state(self) -> None:
        profiles = (
            (
                "ai/.bin/omp-profile",
                "codex",
                self.home / ".omp/agent/config.yml",
                self.home / ".omp/agent/.active",
            ),
            (
                "ai/.bin/opencode-profile",
                "gpt",
                self.home / ".config/opencode/opencode.jsonc",
                self.home / ".config/opencode/.active",
            ),
        )

        for script, profile, config, active in profiles:
            config.parent.mkdir(parents=True, exist_ok=True)
            config.write_text("user configuration\n")
            completed = self.run_command(script, "use", profile, expected_code=1)
            self.assertIn("refusing to overwrite unmanaged config", completed.stderr)
            self.assertEqual("user configuration\n", config.read_text())
            config.unlink()

            external_state = self.home / f"{profile}-external-state"
            external_state.write_text("user state\n")
            active.symlink_to(external_state)
            completed = self.run_command(script, "use", profile, expected_code=1)
            self.assertIn("refusing to overwrite unmanaged active profile", completed.stderr)
            self.assertEqual("user state\n", external_state.read_text())
            active.unlink()
            active.write_text("unmanaged state\n")
            completed = self.run_command(script, "use", profile, expected_code=1)
            self.assertIn("refusing to overwrite unmanaged active profile", completed.stderr)
            self.assertEqual("unmanaged state\n", active.read_text())
            active.write_text("common\n")
            completed = self.run_command(script, "use", profile, expected_code=1)
            self.assertIn("refusing to overwrite unmanaged active profile", completed.stderr)
            self.assertEqual("common\n", active.read_text())
            self.assertFalse(config.exists())

    def test_omp_profile_removes_migrated_checkout_state(self) -> None:
        before = self.repository_status()

        with tempfile.TemporaryDirectory() as temporary:
            dotfiles = Path(temporary)
            legacy_directory = dotfiles / "ai/pi"
            legacy_directory.mkdir(parents=True)
            omp_directory = dotfiles / "ai/omp"
            omp_directory.mkdir(parents=True)
            (omp_directory / "profiles").symlink_to(
                ROOT / "ai/omp/profiles", target_is_directory=True
            )
            (omp_directory / "merge-profile.py").symlink_to(
                ROOT / "ai/omp/merge-profile.py"
            )
            (dotfiles / "dotbot").symlink_to(ROOT / "dotbot", target_is_directory=True)
            legacy_files = (
                legacy_directory / "config.yml",
                legacy_directory / ".active",
                legacy_directory / "config.yml.lock",
            )
            legacy_files[0].write_text(
                "# Generated by pi-profile from ai/pi/profiles/common.yml + ai/pi/profiles/codex.yml.\n"
            )
            legacy_files[1].write_text("codex\n")
            legacy_files[2].touch()

            completed = subprocess.run(
                [str(ROOT / "ai/.bin/omp-profile"), "use", "codex"],
                text=True,
                capture_output=True,
                cwd=ROOT,
                env={**self.environment, "DOTFILES": str(dotfiles)},
                check=False,
            )
            self.assertEqual(0, completed.returncode, completed.stderr)
            self.assertTrue(all(not path.exists() for path in legacy_files))

        self.assertEqual(before, self.repository_status())

    def test_opencode_profile_removes_migrated_checkout_state(self) -> None:
        before = self.repository_status()

        with tempfile.TemporaryDirectory() as temporary:
            dotfiles = Path(temporary)
            opencode_directory = dotfiles / "ai/opencode"
            opencode_directory.mkdir(parents=True)
            (opencode_directory / "profiles").symlink_to(
                ROOT / "ai/opencode/profiles", target_is_directory=True
            )
            (opencode_directory / "merge-profile.py").symlink_to(
                ROOT / "ai/opencode/merge-profile.py"
            )
            legacy_files = (
                opencode_directory / "opencode.jsonc",
                opencode_directory / ".active",
            )
            legacy_files[0].write_text(
                "// Generated by opencode-profile from ai/opencode/profiles/common.jsonc + ai/opencode/profiles/gpt.jsonc.\n"
            )
            legacy_files[1].write_text("gpt\n")

            completed = subprocess.run(
                [str(ROOT / "ai/.bin/opencode-profile"), "use", "gpt"],
                text=True,
                capture_output=True,
                cwd=ROOT,
                env={**self.environment, "DOTFILES": str(dotfiles)},
                check=False,
            )
            self.assertEqual(0, completed.returncode, completed.stderr)
            self.assertTrue(all(not path.exists() for path in legacy_files))

        self.assertEqual(before, self.repository_status())

    def test_omp_profile_tooling_preserves_unmanaged_config(self) -> None:
        config = self.home / ".omp/profiles/codex/agent/config.yml"
        config.parent.mkdir(parents=True)
        config.write_text("user profile settings\n")

        completed = self.run_command(
            "dotbot/bin/dotbot",
            "-d",
            str(ROOT),
            "-c",
            "ai.yaml",
            "--only",
            "shell",
            expected_code=1,
        )

        self.assertIn(
            "Refusing to overwrite unmanaged OMP profile config",
            completed.stderr or completed.stdout,
        )
        self.assertEqual("user profile settings\n", config.read_text())

    def test_omp_profile_tooling_preserves_linked_profile_directory(self) -> None:
        profiles = self.home / ".omp/profiles"
        profiles.mkdir(parents=True)
        external = self.home / "external-codex"
        external.mkdir()
        (profiles / "codex").symlink_to(external, target_is_directory=True)

        completed = self.run_command(
            "dotbot/bin/dotbot",
            "-d",
            str(ROOT),
            "-c",
            "ai.yaml",
            "--only",
            "shell",
            expected_code=1,
        )

        self.assertIn(
            "Refusing to use linked OMP profile directory",
            completed.stderr or completed.stdout,
        )
        self.assertFalse((external / "agent").exists())


    def test_make_ai_is_idempotent_without_dirtying_checkout(self) -> None:
        before = self.repository_status()
        repository_envrc = ROOT / "base/.envrc"
        if not (repository_envrc.exists() or repository_envrc.is_symlink()):
            local_envrc = self.home / ".envrc"
            local_envrc.write_text("\n")
            repository_envrc.symlink_to(local_envrc)
            self.addCleanup(repository_envrc.unlink)

        legacy_links = {
            self.home / ".agents/skills/pr-review-draft": ROOT
            / "ai/.agents/skills/pr-review-draft",
            self.home / ".claude/skills/pr-review-draft": ROOT
            / "ai/.agents/skills/pr-review-draft",
            self.home / ".omp/agent/config.yml": ROOT / "ai/pi/config.yml",
            self.home / ".config/opencode/opencode.jsonc": ROOT
            / "ai/opencode/opencode.jsonc",
        }
        for link, target in legacy_links.items():
            link.parent.mkdir(parents=True, exist_ok=True)
            link.symlink_to(target)

        self.run_command("make", "ai")
        self.run_command("make", "ai")

        self.assertEqual(before, self.repository_status())
        self.assertFalse((self.home / ".agents/skills/pr-review-draft").is_symlink())
        self.assertFalse((self.home / ".claude/skills/pr-review-draft").is_symlink())
        self.assertFalse((self.home / ".omp/agent/config.yml").is_symlink())
        self.assertFalse(
            (self.home / ".config/opencode/opencode.jsonc").is_symlink()
        )
        pi_settings = self.home / ".pi/agent/settings.json"
        self.assertTrue(pi_settings.is_file())
        self.assertFalse(pi_settings.is_symlink())
        self.assertEqual(
            "openai-codex", json.loads(pi_settings.read_text())["defaultProvider"]
        )
        self.assertFalse(
            (self.home / ".claude/commands/pr-review-draft.md").exists()
        )
        opencode_agents = self.home / ".config/opencode/AGENTS.md"
        self.assertTrue(opencode_agents.is_symlink())
        self.assertEqual((ROOT / "ai/AGENTS.md").resolve(), opencode_agents.resolve())
        omp_agents = self.home / ".omp/agent/AGENTS.md"
        self.assertTrue(omp_agents.is_symlink())
        self.assertEqual((ROOT / "ai/AGENTS.md").resolve(), omp_agents.resolve())
        pi_agents = self.home / ".pi/agent/AGENTS.md"
        self.assertTrue(pi_agents.is_symlink())
        self.assertEqual((ROOT / "ai/AGENTS.md").resolve(), pi_agents.resolve())
        for definition in (
            self.home / ".claude/agents/executor.md",
            self.home / ".omp/agent/agents/explore.md",
            self.home / ".pi/agent/agents/explore.md",
            self.home / ".config/opencode/agents/explore.md",
            self.home / ".codex/agents/executor.toml",
        ):
            self.assertTrue(definition.is_file(), definition)
            self.assertFalse(definition.is_symlink(), definition)

        codex_profile = self.home / ".omp/profiles/codex/agent"
        codex_config = codex_profile / "config.yml"
        self.assertTrue(codex_config.is_file())
        self.assertFalse(codex_config.is_symlink())
        self.assertIn("startup:\n  quiet: true", codex_config.read_text())
        self.assertIn(
            "default: openai-codex/gpt-5.6-sol:medium",
            codex_config.read_text(),
        )
        for name, source in (
            ("AGENTS.md", ROOT / "ai/AGENTS.md"),
            ("models.yml", ROOT / "ai/omp/models.yml"),
            ("keybindings.yml", ROOT / "ai/omp/keybindings.yml"),
            ("mcp.json", ROOT / "ai/omp/mcp.json"),
            ("WATCHDOG.md", ROOT / "ai/WATCHDOG.md"),
            ("agents", self.home / ".omp/agent/agents"),
        ):
            installed = codex_profile / name
            self.assertTrue(installed.is_symlink(), installed)
            self.assertEqual(source.resolve(), installed.resolve())

if __name__ == "__main__":
    unittest.main()
