[tools]
biome = "latest"
bun = "latest"
cosign = "latest"
gh = "latest"
go = "latest"
node = "latest"
python = "latest"
rust = "latest"
slsa-verifier = "latest"
task = "latest"
uv = "latest"
"npm:@anthropic-ai/claude-code" = "latest"

[settings]
disable_backends = ["asdf", "pipx", "npm"]
pipx.uvx = true
npm.bun = true
