[tools]
biome = "latest"
bun = "latest"
cosign = "latest"
elixir = "latest"
erlang = "latest"
gh = "latest"
go = "latest"
node = "latest"
rust = "latest"
slsa-verifier = "latest"
task = "latest"
uv = "latest"

[settings]
disable_backends = ["asdf", "pipx", "npm"]
pipx.uvx = true
npm.bun = true
