[tools]
bun = "latest"
elixir = "latest"
erlang = "latest"
go = "latest"
node = "latest"
rust = "latest"
task = "latest"
uv = "latest"
# "npm:@anthropic-ai/claude-code" = "latest"
# "npm:@biomejs/biome" = "latest"

[settings]
disable_backends = ["asdf", "pipx", "npm"]
pipx.uvx = true
npm.bun = true
