#:schema https://mise.en.dev/schema/mise.json

[tools]
# dev
go = "latest"
rust = "latest"
python = "latest"
uv = "latest"
node = "latest"
bun = "latest"
k9s = "latest"
gh = "latest"
biome = "latest"

# ai
claude = "latest"
opencode = "latest"
"npm:ocx" = "latest"
"npm:@rynfar/meridian" = "latest"
"github:can1357/oh-my-pi" = "latest"
ast-grep = "latest"

# lsp
"go:golang.org/x/tools/gopls" = "latest"
"npm:pyright" = "latest"
ruff = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:yaml-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
marksman = "latest"
taplo = "latest"
lua-language-server = "latest"
erlang = "latest"
elixir = "latest"
"github:elixir-lsp/elixir-ls" = { version = "latest", postinstall = "ln -sf \"$MISE_TOOL_INSTALL_PATH/language_server.sh\" \"$MISE_TOOL_INSTALL_PATH/elixir-ls\"" }

# containers
lima = "latest"
colima = "latest"
docker-cli = "latest"

[tools.docker-compose]
version = "latest"
postinstall = '''
mkdir -p ~/.docker/cli-plugins ~/.local/bin
compose_plugin="$(which docker-cli-plugin-docker-compose)"
ln -sf "$compose_plugin" ~/.docker/cli-plugins/docker-compose
ln -sf "$compose_plugin" ~/.local/bin/docker-compose
'''

[settings]
disable_backends = ["pipx"]
pipx.uvx = true
npm.package_manager = "bun"
experimental = true
github.credential_command = "gh auth token"
