---
name: Lint

on: # yamllint disable-line rule:truthy
  pull_request:
  push:

permissions:
  contents: read

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip3 install yamllint

      - name: Lint yaml
        run: |
          yamllint .

  shell:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@v3
        with:
          severity: error
          token: ${{ secrets.GITHUB_TOKEN }}
