quitOnTopLevelReturn: true

git:
  diffRenderers:
    - command: delta --dark --line-numbers --paging=never

gui:
  showBottomLine: false
  showCommandLog: false
  filterMode: fuzzy
  showListFooter: false
  sidePanels:
    - [files, worktrees, submodules]
    - [branches, remotes, tags]
    - [commits, reflog]
    - [stash]
